http:
  listner:
    host: "localhost"
    port: "9081"
    path: "/TravelOnTipExternalSystem/{serviceType}"
Db:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "Sofonn4*qt!"
  database: "MulesoftRealTimeProject"
    